spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb+srv://username:password@cluster0.p6zisdp.mongodb.net/activitydb?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    topic:
      name: activity-events

server:
  port: 8082

strava:
  client-id: 211212
  client-secret: key
  redirect-uri: http://localhost:8082/login/oauth2/code/strava

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true