spring:
  application:
  name: Eureka

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # Server does not register itself
    fetch-registry: false # Server does not fetch registry from other servers
